[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nonebot-plugin-doroending"
version = "0.2.0"
description = "获取今日的doro结局"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{name = "踏水寻", email = "1264405841@qq.com"}]
dependencies = [
    "nonebot2>=2.4.0",
    "nonebot_plugin_localstore",
    "aiohttp>=3.13.0",
    "aiofiles>=23.2.0",
    "nonebot-plugin-alconna>=0.61.1",
    "nonebot-plugin-uninfo>=0.11.0",
]

[project.entry-points."nonebot.plugin"]
doroending = "nonebot_plugin_doroending"

[tool.setuptools]
packages = ["nonebot_plugin_doroending"]